spring.messages.basename=messages

spring.datasource.url=jdbc:mysql://localhost:3306/vod
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=mysql

spring.jpa.show-sql=true

management.endpoints.web.exposure.include=*
management.endpoint.shutdown.enabled=true

management.info.env.enabled=true
info.app.name=library-app
info.app.version=1.0.0
info.app.description=Library application